# .gitlab-ci.yml

stages:
  - build
  - test
  - deploy

variables:
  APP_NAME: "myapp"
  ENVIRONMENT: "production"

before_script:
  - echo "Setting up environment"

build_job:
  stage: build
  script:
    - echo "Building the application"

test_job:
  stage: test
  script:
    - echo "Running tests"

deploy_job:
  stage: deploy
  script:
    - echo "Deploying to $ENVIRONMENT"